#!/bin/bash

DIR="/Users/tbenzige/Projects/aws"
URL="http://awes0.me"
BASE=`basename $1`

cp $1 $DIR
cd $DIR
git add $BASE
git commit -m "$BASE added"
git push origin gh-pages
echo "$URL/$BASE" | pbcopy