#!/bin/bash

DIR="/Users/tbenzige/Projects/aws" # Path to gh-pages repo
URL="http://awes0.me" # Domain and path to where the GitHub Page lives on the web
BASE=`basename $1`

cp $1 $DIR
cd $DIR
git add $BASE
git commit -m "$BASE added"
git push origin gh-pages
echo "$URL/$BASE" | pbcopy